# AUTHENTICATION

ACCESS_TOKEN = 'PUT_YOUR_TOKEN_HERE'
CLIENT_ID = 'PUT_YOUR_CLIENT_ID_HERE'
CLIENT_SECRET = 'PUT_YOUR_CLIENT_SECRET_HERE'

# CONFIGURATION

ACTIVE = False
LINK_TYPE_VALUE = 1
WIDTH_VALUE = 640

# CONFIGURATION VALIDATION

LINK_TYPE_OPTIONS = {
    0: 'link',
    1: 'link_with_play_button'
}

LINK_TYPE = LINK_TYPE_OPTIONS.get(LINK_TYPE_VALUE, 'link')

WIDTH_OPTIONS = {
    640: 640,
    960: 960,
    1280: 1280,
    1920: 1920
}

WIDTH = WIDTH_OPTIONS.get(WIDTH_VALUE, 640)

# API

API_URL = 'https://api.vimeo.com/videos/{}/pictures'
